name: CI - Multi Container App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build containers
        run: docker compose build

      - name: Run containers
        run: docker compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Test Flask health endpoint
        run: curl --fail http://localhost:5000/health
